export const ALLOWED_PROFILE_FIELDS = [
    "phone",
    "cityCountry",
    "linkedInUrl",
    "githubUrl",
    "portfolioUrl",
    "targetRole",
    "yearsExperience",
    "currentStatus",
    "degree",
    "university",
    "graduationYear",
    "cgpa",
    "coreSkills",
    "preferredIndustry",
    "interviewFocus",
    "careerGoal",
    "avatarDataUrl",
] as const;