export const VIOLATION_TYPES = [
    "NO_FACE_DETECTION",
    "MULTIPLE_FACES",
    "LOOKING_AWAY",
    "COPY_PASTE",
    "TAB_SWITCH",
    "SNAP_MODE",
    "DEVICE_DISCONNECTED",
    "EXTERNAL_AUDIO_DETECTED",
    "SCREEN_SHARING_START",
    "FULLSCREEN_EXIT",
] as const;
